# Лекция 3. Сравнтельная геномика 

если нет отбора - долдно быть больше несинонимичных мутаций (просто из-з атого, что синонимичесные - только в третье кодоне) но под дейтивем отбора все-таки больше синонимичеых. Значит несинонимичные мутации вредны

А когда синонимичная мутация закрепляется - это полоиьлеьный отбор . это очень редкий случай и очень интересен. 

если ассомтерть иммунитет ASG15 - потеря одного цистеина приводит к тому, тчо не образуется гомодимер, необдхоимый для выхода белка во внеклетоынй маткрис и борьбы с ковидом. 

и напрмер летучие мыши - он долден стремительно ращвиваться и если там появляется жесткий очищающий отбор - это интресно

и такие явления можно фиксировать смотря на показатели синонимичых и несинонимичных мутаци 

# dN/dS

dN - отношение наблюдаемого количтсва позциий несинонимичных мутаций к количеству позиций в которых это вообще мозможно наблюдать в такой последоватлеьности 

dS - тоже самое для синонимичных мутаций 

можно интерпретировать кака отношение "ненейральных" замен к "нейтральным"

и если dN >> dS - положилеьный отбор. 

если меньше - несинонимичные мутации вычищаются. 

= 1 нейтральаня эволюция



# пример 

он довольно простой, в релаьности важно строить филогенетичнское дерево, более сложные методы используют и оптимизируют длины ветвей 

пусть есть 2 последоватльнности ACT CCG GGG CCC и ACG CCG GGC CTC 
синонимичнеы - в первом и третьей кодоне, всего их могло быть 4

dS = 2/4 = 1/2

dN = 1/8(первые две позиции в каждом кодоне)

dN/dS = 1/4 - отбор очищающий

# пример 2


CGT CGT CCA CTT GTA 
CGT GGC GCA CTT GTA 

все зависит от порядка мутаций 

CGT > CGC > GGC
CGT > GGT > GGC

в любом случае для этого кодона 1 несинонимичная и 1 синонимичная 

dN = 2/10 dS = 1/5 
dS = 1/5 

dN/dS = 1


# Проблемы наивного подход а
но если мы рассматриваем гены целиком и большого числа доменов, потому что картина усреднются и мы не увидим отбор . пожтому так не считаем и исопльзуем более утонченный рассчет  + бвают ошибки секыенирования, которые могут сльно влиять на результат 

# тест McDonald-Kreitman

смотрим на разницу в dN/dS внутри современной попцляии и медлу современными и предклвыми видми

исрпльзуется в контексте эволюционной нейробиологии (например люди и обезьяны)

найти популяцонныне данные для людей просто - а для ослаьных видов оч сложно 

прмиер 
1 вид
CTT ACT TAT ACC CGT
CTG ACT TAT ACC CGT
CTG ACT TCT ACC CGT
CTG ACT TCT ACA CGT

2 вид
ATG ACC TCT ACC CGT

внутри | меж
N 1 (b)|1(a)
S 3(d)|1(c)

если несинонимичные мтуации нейтральны то a/c = b/d 
еслси полезны то a/c> b/d (между видами больше чем внутри вида)
оратная ситацяи почти не бывает (положительный отбор очень редок)

в итоге при сравнении оюдлей и шимпанзе было 304 гена с положительным отбором (иммунитет, формирование гамет, сенсорное воспряитие), 813 с очищающим (то что не должно меняться).

# jukes-cantor кореркция

она нужна для ситаций с множетсвенными заменами - один сайт может сперва мутировать а потом мутировать обратно 

# одни замены чаще возникают чем лругие 

перезод междлу пуринами проще чем медлу пуринами и пиридмидмнами, пожмтоу неоткорые замены возникают чаще 

мы можем это учитывать и исопльзовать матрицы замен 

наримре blossom 62

# марковские цепи

этовсе поъоже на марковские цепи

пусть есть состояние - исходная аминокислота. пусть есть вероятность замнеы и есть вероятность перейти в другую амикосилоту. 

и тогда получится матрица пере=одов - например muse-Gaut MG64

есть парамтеры alpha и betta, alpha approx dS , alpha approx dN и поэтому b\a = dN/dS

и иногда dN/dS обозначнают w = b/a

# Деревья

больше важна правильаня топология, чем длины ветвей. 

например root-to-tip - длина от корня до организма . если это расстояния очень отличается от отсльаных - какая-то ошибка 

и такде для кадлого листа считаем dN/dS и усредняем для всего вида 



# уровни отбора 

# branch-site модели

HYPHY (busted и все варианты) и PAML (M2а 3 класса vs M1a) - один и тот же пакет в разных реализациях

foreground группа - 3 w класса (есть >1) и backgroud группа - 2w класса (=1 и <1)

вариант с 3w класса на foreground и с 2 на той же группе сравниаемся с помошью LRT (likelihood ratio test) 

качество моедлей оценивается с поомщью AIC (aikake information criterion)

при анализе важна длина генов

# отбор на уровне ветвей

HYPHY aBSREL - по аналогии с картинкой по горизотали

испольуюя AIC подбирается оптимальное клоичество классво r для каждой ветви 

удобно если мы знаем что в гене был пол отбор и хотим узнать когда он возник

# отбор на уровне сайтов 

HYPHY MEME - по аналогии с картинкой - вертикаль

mixed effects model of evolution 

aplha - синонимичный рейт
betta- - несинонимичный рейт background betta- <= alpha
betta+ - несинонимичный рейт по сути foregroung

в итоге мы от общего идем к частному 

# BUSTED-E 

по аналогии скартинкой - просто кусочек 

minus the error 

часто w может достигать безумных значений изза

ошибок MSA
ошибрк секвнирования

вводятся ограничения w [100, 1e10] и pe [0,0.1]

в итоге фолз позитивы значительно снижаются 

# бытовые мудроти 

если w>50 = считай бесконечно, не могло возникнуть биологически

root-to-tip можно выислить черех MG64, ничего слонее тту не надо исп

BUSTED-E всегда лучше чнм BUSTED 

# инструмнты

Datamonkey веб туд на котором могут запускаться основные HYPHY методы (дерево надо вшивать в конец fasya файла)

HYPHY Vision - визуализатор результатов котоыре податся в формате json

Phyphy питоновская обертка для HYPHY - плохо рабоатет, лучше поставить hyphy 

# что важно?

хороший инпут

хорошее MSA - максиамльно качестыенное, любая ошидка может вести к ложноположиельынм резам MASCE PAL2NAL

дерево - главное получить реальную топологию (длина ветвей может менятья) IQTREE и тд











